"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {Copy,Check,Plus,Download,RefreshCw,Users,ExternalLink} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Table,TableBody,TableHead,TableHeader,TableRow,TableCell} from "@/components/ui/table";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia} from "@/components/ui/empty";
import {Skeleton} from "@/components/ui/skeleton";
import {Toaster,toast} from "sonner";
type Guest={id:string;name:string;link:string;sent:number;attendance:string|null;message:string|null;updated_at:string|null};
type Reply={id:string;name:string;attendance:string;message:string;updated_at:string;guest_id:string|null};
function badge(s:string|null){return <span className={"status-badge "+(s==="Hadir"?"yes":s==="Tidak hadir"?"no":s==="Masih ragu"?"maybe":"")}>{s||"Belum konfirmasi"}</span>}
export default function Dashboard(){const[guests,setGuests]=useState<Guest[]>([]),[replies,setReplies]=useState<Reply[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState("Semua"),[add,setAdd]=useState(false),[names,setNames]=useState(""),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState(""),[copied,setCopied]=useState(""),[page,setPage]=useState(0),[rowBusy,setRowBusy]=useState("");const pending=useRef<{text:string;items:{id:string;name:string}[]}|null>(null);
async function load(){setLoading(true);setError("");try{const r=await fetch("/api/owner/guests",{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p.error||"Daftar tamu belum dapat dimuat.");setGuests(p.guests);setReplies(p.replies)}catch(e){setError(e instanceof Error?e.message:"Tidak dapat memuat data.")}finally{setLoading(false)}}
useEffect(()=>{load()},[]);useEffect(()=>{setPage(0)},[search,filter]);
const filtered=useMemo(()=>guests.filter(g=>g.name.toLowerCase().includes(search.toLowerCase())&&(filter==="Semua"||(filter==="Belum konfirmasi"?!g.attendance:filter==="Belum dikirim"?!g.sent:g.attendance===filter))),[guests,search,filter]);
const lines=names.split(/\r?\n/).map(n=>n.trim()).filter(Boolean);
async function save(e:React.FormEvent){e.preventDefault();if(lines.length>200||lines.some(n=>n.length>160)){setSaveError("Maksimal 200 nama; setiap nama maksimal 160 karakter.");return}setSaving(true);setSaveError("");if(!pending.current||pending.current.text!==names)pending.current={text:names,items:lines.map(name=>({id:crypto.randomUUID(),name}))};try{const r=await fetch("/api/owner/guests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({guests:pending.current.items})});const p=await r.json();if(!r.ok)throw new Error(p.error);setNames("");pending.current=null;setAdd(false);toast.success("Nama tamu dan link undangan tersimpan.");await load()}catch(e){setSaveError(e instanceof Error?e.message:"Belum tersimpan. Coba lagi.")}finally{setSaving(false)}}
async function copy(value:string,id:string){try{await navigator.clipboard.writeText(value);setCopied(id);setTimeout(()=>setCopied(""),2200);toast.success("Berhasil disalin.")}catch{toast.error("Tidak dapat menyalin otomatis. Pilih dan salin link yang ditampilkan.")}}
async function mark(g:Guest){setRowBusy(g.id);try{const r=await fetch("/api/owner/guests",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:g.id,sent:!g.sent})});if(!r.ok){const p=await r.json();throw new Error(p.error)}setGuests(gs=>gs.map(x=>x.id===g.id?{...x,sent:g.sent?0:1}:x))}catch(e){toast.error(e instanceof Error?e.message:"Status belum tersimpan.")}finally{setRowBusy("")}}
function sheetCell(v:unknown){let s=String(v??"").replace(/[\t\r\n]+/g," ");if(/^[=+@-]/.test(s))s="'"+s;return s}
function copySheet(){const rows:unknown[][]=[["Nama Tamu","Link Undangan","Status Kirim","Kehadiran","Ucapan"]];guests.forEach(g=>rows.push([g.name,g.link,g.sent?"Sudah dikirim":"Belum dikirim",g.attendance||"Belum konfirmasi",g.message||""]));copy(rows.map(r=>r.map(sheetCell).join("\t")).join("\n"),"sheets")}
return <main className="owner-page"><Toaster position="top-center"/><div className="owner-wrap"><header className="owner-header"><div><p className="owner-eyebrow">Dilla &amp; Bobby · 04.10.26</p><h1>Dashboard Undangan</h1></div><a href="/" target="_blank" rel="noreferrer">Lihat undangan ↗</a></header><div className="owner-toolbar"><Button onClick={()=>setAdd(true)}><Plus size={16}/> Tambah Tamu</Button><Button variant="outline" onClick={load} disabled={loading}><RefreshCw size={15}/> Perbarui</Button></div>
<div className="owner-stats">{[["Tamu di daftar",guests.length],["Sudah dikirim",guests.filter(g=>g.sent).length],["Konfirmasi hadir",replies.filter(r=>r.attendance==="Hadir").length],["Semua konfirmasi",replies.length]].map(([label,n])=><div className="stat" key={label}>{loading?<Skeleton className="h-9 w-16"/>:<strong>{n}</strong>}<span>{label}</span></div>)}</div>
{error&&<div className="owner-error" role="alert">{error} <button onClick={load}>Coba lagi</button></div>}
<Tabs defaultValue="guests" className="owner-tabs"><TabsList><TabsTrigger value="guests">Daftar Tamu</TabsTrigger><TabsTrigger value="replies">RSVP &amp; Ucapan</TabsTrigger><TabsTrigger value="sheet">Spreadsheet</TabsTrigger></TabsList>
<TabsContent value="guests"><section className="owner-card"><div className="owner-toolbar"><Input className="owner-search" aria-label="Cari nama tamu" placeholder="Cari nama tamu…" value={search} onChange={e=>setSearch(e.target.value)}/><Select value={filter} onValueChange={setFilter}><SelectTrigger aria-label="Filter tamu"><SelectValue/></SelectTrigger><SelectContent>{["Semua","Hadir","Tidak hadir","Masih ragu","Belum konfirmasi","Belum dikirim"].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div>
{loading?<div className="grid gap-3 py-6">{[0,1,2].map(i=><Skeleton className="h-14 w-full" key={i}/>)}</div>:filtered.length?<><Table className="owner-table"><TableHeader><TableRow><TableHead>Nama &amp; link undangan</TableHead><TableHead>Kehadiran</TableHead><TableHead>Status kirim</TableHead><TableHead>Tindakan</TableHead></TableRow></TableHeader><TableBody>{filtered.slice(page*25,(page+1)*25).map(g=><TableRow key={g.id}><TableCell style={{whiteSpace:"normal"}}><div className="guest-name">{g.name}</div><a href={g.link} target="_blank" rel="noreferrer">{g.link}</a></TableCell><TableCell>{badge(g.attendance)}</TableCell><TableCell><Button size="sm" variant="ghost" disabled={rowBusy===g.id} onClick={()=>mark(g)}>{g.sent?<><Check size={14}/> Terkirim</>:"Tandai terkirim"}</Button></TableCell><TableCell><div className="owner-row-actions"><Button size="sm" variant="outline" onClick={()=>copy(g.link,g.id)}>{copied===g.id?<Check size={14}/>:<Copy size={14}/>} Link</Button></div></TableCell></TableRow>)}</TableBody></Table><div className="owner-pager"><span>{filtered.length} tamu · Halaman {page+1} / {Math.max(1,Math.ceil(filtered.length/25))}</span><div className="owner-row-actions"><Button size="sm" variant="outline" disabled={!page} onClick={()=>setPage(p=>p-1)}>Sebelumnya</Button><Button size="sm" variant="outline" disabled={(page+1)*25>=filtered.length} onClick={()=>setPage(p=>p+1)}>Berikutnya</Button></div></div></>:<Empty><EmptyHeader><EmptyMedia variant="icon"><Users/></EmptyMedia><EmptyTitle>{guests.length?"Tidak ada hasil":"Daftar tamu masih kosong"}</EmptyTitle><EmptyDescription>{guests.length?"Coba nama atau filter lain.":"Tambahkan nama tamu untuk membuat link undangan pribadi."}</EmptyDescription></EmptyHeader>{!guests.length&&<Button onClick={()=>setAdd(true)}>Tambah Tamu</Button>}</Empty>}
</section></TabsContent>
<TabsContent value="replies"><section className="owner-card"><h2>Konfirmasi &amp; doa untuk kalian</h2><p>Konfirmasi disimpan di sini, termasuk dari tamu yang membuka link umum.</p>{loading?<Skeleton className="h-24 w-full mt-6"/>:replies.length?replies.map(r=><article className="owner-message" key={r.id}><div className="owner-toolbar"><strong>{r.name}</strong>{badge(r.attendance)}</div>{r.message&&<p>{r.message}</p>}<small>{new Date(r.updated_at).toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Jakarta"})} WIB</small></article>):<Empty><EmptyHeader><EmptyTitle>Belum ada konfirmasi</EmptyTitle><EmptyDescription>RSVP dan ucapan akan muncul setelah tamu mengisi undangan.</EmptyDescription></EmptyHeader></Empty>}</section></TabsContent>
<TabsContent value="sheet"><section className="owner-card"><h2>Daftar tamu &amp; link</h2><p>Nama tamu, link undangan, status kirim, kehadiran, dan ucapan dalam satu tabel.</p><div className="owner-toolbar mt-6"><Button variant="outline" onClick={copySheet} disabled={loading||!guests.length}><Copy size={15}/> {copied==="sheets"?"Tabel tersalin":"Salin Tabel untuk Sheets"}</Button><Button variant="outline" asChild><a href="/api/owner/export"><Download size={15}/> Unduh CSV</a></Button></div><div className="sheet-note"><strong>Google Sheets belum terhubung</strong>Untuk sementara, salin tabel lalu tempel di sel A1 pada Google Sheets, atau impor file CSV. Salinan ini tidak diperbarui otomatis.</div></section></TabsContent></Tabs>
</div><Dialog open={add} onOpenChange={v=>{if(!saving)setAdd(v)}}><DialogContent><DialogTitle>Tambah nama tamu</DialogTitle><DialogDescription>Tulis satu nama per baris. Setiap nama mendapat link pribadi. Maksimal 200 nama sekaligus.</DialogDescription><form onSubmit={save} className="owner-bulk"><Textarea value={names} onChange={e=>setNames(e.target.value)} placeholder={"Bapak Andi dan Keluarga\nIbu Rina\nSahabat Dilla & Bobby"} required aria-label="Nama tamu, satu per baris"/><p className="owner-count">{lines.length} nama</p>{saveError&&<p className="owner-error" role="alert">{saveError}</p>}<Button disabled={saving||!lines.length||lines.length>200}>{saving?"Menyimpan…":"Simpan & Buat Link"}</Button></form></DialogContent></Dialog></main>}
